name: Test, Build, and Push Docker image

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t git-image

      - name: Log in to Docker
        env:
          docker_user: ${{secrets.DOCKER_USERNAME}}
          docker_pass: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $docker_user -p $docker_pass

      - name: Generate tag number
        run: echo "TIME_NOW=$(date +%s)" >> $GITHUB_ENV

      - name: Push to Docker Hub
        run: |
          docker tag git-image conormgomes/liatrio-exercise-docker:$TIME_NOW
          docker push conormgomes/liatrio-exercise-docker:$TIME_NOW
          docker tag git-image conormgomes/liatrio-exercise-docker:latest
          docker push conormgomes/liatrio-exercise-docker:latest

      - name: Run js code to open endpoint
        run: docker run -dp 172.17.0.1:80:80 git-image

      - name: Run tests
        uses: liatrio/github-actions/apprentice-action@0b41561cca6822cc8d880fe0e49e7807a41fdf91

      - name: Install Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: ${{secrets.GCLOUD_EMAIL}}
          credentials_json: ${{secrets.GCLOUD_KEY}}
          project_id: liatrio-exercise-cloud

      - name: Deploy Revision to Google Cloud Run
        run: |
          gcloud run deploy liatrio-exercise --image docker.io/conormgomes/liatrio-exercise-docker:$TIME_NOW
