name: Test, Build, and Push Docker image

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: docker-container
        run: docker build . -t git-image

      - name: Log in to Docker
        env:
          docker_user: ${{secrets.DOCKER_USERNAME}}
          docker_pass: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $docker_user -p $docker_pass

      - name: Generate tag number
        run: echo "TIME_NOW=$(date +%s)" >> $GITHUB_ENV

      - name: Push to Docker Hub
        run: |
          docker tag git-image conormgomes/liatrio-exercise-docker:$TIME_NOW
          docker push conormgomes/liatrio-exercise-docker:$TIME_NOW

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '21.7.3'

      - name: Install Node + Express
        working-directory: src
        run: |
          npm install
          npm install express

      - name: Run js code to open endpoint
        working-directory: src
        run: node index.js

      - name: Run tests
        uses: liatrio/github-actions/apprentice-action@master